uploads = []
generated = []

[[outputs]]
id = "Ck8wGhgXYjczitry4jxm9"
uri = "file://CAREi_source.txt"
type = "text"
title = "CAREi — Full Source Code"

[[outputs]]
id = "jIpR80BIOvOjJf_TmvlM8"
uri = "file://CAREi-Source-Code.md"
type = "text"
title = "CAREi-Source-Code.md"

[[outputs]]
id = "YNe5ZqolrSyn1IWGiV6IU"
uri = "file://carei-app-source.tar.gz"
type = "unspecified"
title = "CAREi App — Full Source Code"
