uploads = []
generated = []

[[outputs]]
id = "Ck8wGhgXYjczitry4jxm9"
uri = "file://CAREi_source.txt"
type = "text"
title = "CAREi — Full Source Code"

[[outputs]]
id = "jIpR80BIOvOjJf_TmvlM8"
uri = "file://CAREi-Source-Code.md"
type = "text"
title = "CAREi-Source-Code.md"

[[outputs]]
id = "YNe5ZqolrSyn1IWGiV6IU"
uri = "file://carei-app-source.tar.gz"
type = "unspecified"
title = "CAREi App — Full Source Code"

[[outputs]]
id = "7up7YnjAyMjkTgKyf6iUw"
uri = "file://carei-app-source.zip"
type = "unspecified"
title = "CAREi App — Source Code (.zip, 214 KB)"

[[outputs]]
id = "Km47x5RtjUoWAGSnRXvq2"
uri = "file://CAREi-source.zip"
type = "unspecified"
title = "CAREi Source Code"

[[outputs]]
id = "eFgt9DPcTaVvhTxldpUbr"
uri = "file://CAREiApp.txt"
type = "text"
title = "CAREiApp.tsx — full source"

[[outputs]]
id = "ma5uIPCnjGf0iAVHb_Mq6"
uri = "file://CAREi-Features.md"
type = "text"
title = "CAREi — Full Feature Overview"
